### ISSUE TITLE
last indexerror: tuple index out of range

### ISSUE THREAD

**Issue by michaellindon** [pytoolz/toolz#424]
Here is a reproducible example:

```
foo = zip([1,2,3],[4,5,6])
last(foo)
last(foo)
```

The output in my repl looks like this
```
In[43]: foo = zip([1,2,3],[4,5,6])
In[44]: last(foo)
Out[44]: (3, 6)
In[45]: last(foo)
Traceback (most recent call last):
  File "/Users/mlindon/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-45-06bc2d3f7f9e>", line 1, in <module>
    last(foo)
  File "/Users/mlindon/anaconda3/lib/python3.6/site-packages/toolz/itertoolz.py", line 398, in last
    return tail(1, seq)[0]
IndexError: tuple index out of range
```

**Comment by groutr** [comment]
The first call to `last(foo)` consumes the iterator.  After that `foo` is empty.  That is why you get the error.  If you need the penultimate element, you call `tail(2, foo)[0]` or `first(tail(2, foo))`

**Comment by michaellindon** [comment]
I was trying to use it like Clojure, I was expecting things not to have side effects so that last(foo) would return the same result if called twice. I didn't realize last was not a pure function.

**Comment by groutr** [comment]
From what I understand, clojure seq in closure maps to lists/tuples in python and lazy sequences map to iterators in python.  Can you call last() twice on a lazy seq in clojure?

**Comment by michaellindon** [comment]
In clojure last works for any kind of sequence, list, array, lazy list. last always gives the last element and does not mutate the input.
