### ISSUE TITLE
Bug in compose introduced in 0.10.0

### ISSUE THREAD

**Issue by Thomasillo** [pytoolz/toolz#481]
Consider a file temp.py :
```python
import toolz
import functools

print("toolz:", toolz.__version__)

def g(x):
    return x

class A(object):

    def __call__(self):

        _fg = toolz.compose(lambda x:x, g)

        class Inner(object):
            fg = _fg
        return Inner()
    
a = A()()
print(a.fg(2))
```

with toolz 0.9.0:
```
$ python temp.py
toolz: 0.9.0
2
```

With toolz 0.10.0:
```
$ python temp.py
toolz: 0.10.0
Traceback (most recent call last):
  File "temp.py", line 21, in <module>
    print(a.fg(2))
  File "/Users/Thomas/.local/miniconda3/envs/mantik_dev/lib/python3.7/site-packages/toolz/functoolz.py", line 486, in __call__
    ret = self.first(*args, **kwargs)
TypeError: g() takes 1 positional argument but 2 were given
```

In the second example, g gets called with an additional `<__main__.A.__call__.<locals>.Inner` object as first argument.

If not a bug, it's at least a change of behavior breaking code using toolz.

The above example is very reduced and may look strange but is totally sensible in the usecase where it's actually used.

**Comment by ariebovenberg** [comment]
This is due to this change #397 (point 3 in the initial comment).

the cause: `__get__` was implemented to behave similarly to python functions and lambdas. This was also done for `curry`.

@Thomasillo if you want the old behavior, you can use `staticmethod`:

```python
class A:
    myfunc = staticmethod(compose(lambda x: x, lambda x: x))
    mymethod = compose(lambda x: x, lambda x: x)

A.myfunc(3)  # ok
A.mymethod(3)  # not ok
```

@eriknw thoughts?

**Comment by eriknw** [comment]
Sorry to hear this change affected you @Thomasillo.  This affected somebody else too (https://github.com/pytoolz/toolz/issues/460).  We try to keep breaking changes in `toolz` to a bare minimum, so it's time we use semantic versioning.

I think using `staticmethod` is excellent advice, and should work with both newer and later versions of `toolz`.
