### ISSUE TITLE
Importing toolz with 0.11 triggers an internal deprecation warning

### ISSUE THREAD

**Issue by Cadair** [pytoolz/toolz#500]
I have our CI set to error on all warnings and I noticed that when you import toolz 0.11 you raise a deprecation warning about importing your compatibility module.

```
$ python -W error
Python 3.8.5 (default, Sep  5 2020, 10:50:12) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import toolz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stuart/.virtualenvs/sunpy-dev/lib/python3.8/site-packages/toolz/__init__.py", line 3, in <module>
    from .functoolz import *
  File "/home/stuart/.virtualenvs/sunpy-dev/lib/python3.8/site-packages/toolz/functoolz.py", line 9, in <module>
    from .compatibility import PYPY
  File "/home/stuart/.virtualenvs/sunpy-dev/lib/python3.8/site-packages/toolz/compatibility.py", line 2, in <module>
    warnings.warn("The toolz.compatibility module is no longer "
DeprecationWarning: The toolz.compatibility module is no longer needed in Python 3 and has been deprecated. Please import these utilities directly from the standard library. This module will be removed in a future release.
```

**Comment by eriknw** [comment]
Oops!  `toolz` 0.11.1 was just released to fix this.

**Comment by Cadair** [comment]
Thanks for the quick turn around :smile:

**Comment by jakirkham** [comment]
Just merged the conda-forge update PR ( https://github.com/conda-forge/toolz-feedstock/pull/15 ). So should be available soonish (typically 30mins to mirror to CDN).
